name: Voyagers Ultra-Fast Core
on:
  push:
  schedule:
    - cron: '*/30 * * * *' # Relevo de seguridad cada 30 min

jobs:
  ultra-speed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run 15s Cycle
        run: node core/high_frequency.js
